FROM golang:1.11-alpine AS builder

WORKDIR /go/src/github.com/openfaas-incubator/faas-idler

COPY types      types
COPY main.go    main.go
COPY vendor     vendor

RUN apk --no-cache add build-base && \
    go build -o /usr/bin/faas-idler .

FROM alpine:3.10

RUN addgroup -S app && adduser -S -g app app
RUN mkdir -p /home/app

WORKDIR /home/app

COPY --from=builder /usr/bin/faas-idler /home/app/

RUN chown -R app /home/app
USER app

EXPOSE 8080
VOLUME /tmp

ENTRYPOINT ["/home/app/faas-idler"]
